const appTypes = {
    SUBIR_ARCHIVO_EXITO: 'SUBIR_ARCHIVO_EXITO',
    SUBIR_ARCHIVO_ERROR: 'SUBIR_ARCHIVO_ERROR',
    SUBIR_ARCHIVO: 'SUBIR_ARCHIVO',
    CREAR_ENLACE_EXITO: 'CREAR_ENLACE_EXITO',
    CREAR_ENLACE_ERROR: 'CREAR_ENLACE_ERROR',
    MOSTRAR_ALERTA: 'MOSTRAR_ALERTA',
    OCULTAR_ALERTA: 'OCULTAR_ALERTA',
    LIMPIAR_STATE: 'LIMPIAR_STATE',
    AGREGAR_PASSWORD: 'AGREGAR_PASSWORD',
    AGREGAR_DESCARGAS: 'AGREGAR_DESCARGAS'
}

export default appTypes;