const authTypes = {
    USUARIO_AUTENTICADO: 'USUARIO_AUTENTICADO',
    REGISTRO_EXITOSO: 'REGISTRO_EXITOSO',
    REGISTRO_ERROR: 'REGISTRO_ERROR',
    LIMPIAR_ALERTA: 'LIMPIAR_ALERTA',
    LOGIN_EXITOSO: 'LOGIN_EXITOSO',
    LOGIN_ERROR: 'LOGIN_ERROR',
    CERRAR_SESION: 'CERRAR_SESION'
};

export default authTypes;